name: Build and publish

on: 
  workflow_dispatch:
  push:
    branches:
    - main


jobs:
  build:
    name: Get data and build edition templates
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Fetch Data
      run: | 
        ./fetch_data.sh
    - name: Install Saxon, Ant and Python
      run: |
        sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommends
        ./shellscripts/script.sh
        pip install -r requirements.txt
    - name: Build
      run: |
        ant
    - name: Update Favicons
      run: python update_favicons.py

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write      
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4