name: Build and publish

on:
  schedule:
    - cron: "40 23 * * *" 
  workflow_dispatch:
  push:
    branches:
    - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      TYPESENSE_HOST: ${{vars.TYPESENSE_HOST}}
      TYPESENSE_PORT: ${{vars.TYPESENSE_PORT}}
      TYPESENSE_PROTOCOL: ${{vars.TYPESENSE_PROTOCOL}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Fetch Data
      run: | 
        ./shellscripts/fetch_data.sh
    - name: Install Saxon, Ant and Python
      run: |
        sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommends
        ./shellscripts/script.sh
        pip install -r requirements.txt
    - name: Add attributes to root node and denormalize indices
      run: |
       ./shellscripts/attributes_indices.sh
    - name: Build
      run: |
        ant
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    - name: Setup Typesense
      run: |
        python ./pyscripts/make_ts_index.py